apiVersion: apps/v1

kind: Deployment

metadata:

  name: wqf-deployment

spec:

  selector:

    matchLabels:

      app: wqf

  replicas: 2 # tells deployment to run 2 pods matching the template

  template:

    metadata:

      labels:

        app: wqf

    spec:

      containers:

      - name: wqf

        image: ravishankarvblr/kf-demo:latest

        ports:

        - containerPort: 8000
############

