kind: Service
apiVersion: v1
metadata:
  name: wqf-deployment
spec:
  type: LoadBalancer
  ports:
  - name: wqf-deployment
    protocol: TCP
    port: 8000

  selector:
    app: wqf
                        
