apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: sklearn
spec:
  predictors:
  - graph:
      name: classifier
      implementation: SKLEARN_SERVER
      modelUri: s3://sklearn
      envSecretRefName: seldon-init-container-secret
      #modelUri: file:///home/aiap/kf-deploy-git/mlops_kubeflow_mlflow/kubeflow/data/saved_models
      #modelUri: pvc://pvc-3cd28cf3-944f-4f32-bab1-bb10e016785b/opt/saved_models
    name: default
    replicas: 1
    svcOrchSpec:
      env:
      - name: SELDON_LOG_LEVEL
        value: DEBUG
